### ISSUE TITLE
Doesnt render on Flutter web

### ISSUE THREAD

**Issue by sk000007** [shah-xad/flutter_tex#107]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
yes

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
yes

1. Works on android emulator
2. flutter run -> selected chrome...app launches...BUT NO MATH display..
    a. included scripts in index.html as the attached file shows all libraries seems to be loading BUT no rendering..

![Capture](https://user-images.githubusercontent.com/2013582/132969147-cb0531bf-a62f-4e99-b090-4fe4365b0de0.JPG)
![Capture1](https://user-images.githubusercontent.com/2013582/132969256-b3a3a854-0da0-46a0-a671-106b49357b85.JPG)

**Comment by sk000007** [comment]
i am evaluating  flutter_math_fork now and it seems to work ok...not gone into a comparison mode yet ..

**Comment by shah-xad** [comment]
Use this `<script type="text/javascript">window.flutterWebRenderer = "canvaskit";</script>` Don't use this `<script type="text/javascript">window.flutterWebRenderer = "html";</script>` i.e. use `canvaskit` as web renderer.

**Comment by shah-xad** [comment]
It's been resolved.
