### ISSUE TITLE
The backgroundColor property set to Colors.white doesn't work when the Dark Mode of the Android device used for debugging is enabled.

### ISSUE THREAD

**Issue by CodoPixel** [shah-xad/flutter_tex#109]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:**Yes

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer:**Yes

So, here is my problem: when the dark mode is on, the TeXView will **_always_** have a dark background, which is extremly annoying. There is nothing I can do.

I beg you: just add a property to set the theme of the webview.

**Comment by shah-xad** [comment]
As it's based on `webview_flutter` you should follow [this](https://github.com/flutter/flutter/issues/29300).
