### ISSUE TITLE
Page shows webpage not available in release version of app

### ISSUE THREAD

**Issue by Itope84** [shah-xad/flutter_tex#11]
Hi, please when I bundle my demo application for release, inside the container containing the equation, I only get a "webpage" not available message

**Comment by shahxadakram** [comment]
Is it working in debug mode?

**Comment by Itope84** [comment]
Yes

**Comment by shahxadakram** [comment]
Please try latest version `flutter_tex: ^1.0.9`

**Comment by Itope84** [comment]
Hi, thanks for your support. I found the solution and it's not an issue related to the plugin. It's addressed here https://github.com/fluttercommunity/flutter_webview_plugin/issues/339
