### ISSUE TITLE
Engine unable to render the following equations

### ISSUE THREAD

**Issue by Pony-Stark** [shah-xad/flutter_tex#119]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:** yes, 4.0.3

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer:** yes, I am reporting a bug

The engine is unable to render the following strings. It is otherwise working perfectly for other tex strings that I passed into TeXViewDocument:
r"""\(\sec x \cos 5 x+1=0,0<x<\frac{\pi}{2}\)"""
r"""If \(3 \tan \left(x-15^{\circ}\right)=\tan \left(x+15^{\circ}\right), 0<x<90^{\circ}\), find \(x\)"""

**Comment by shah-xad** [comment]
BTW you can try your equations at [Mathjax live Preview](https://www.mathjax.org/#demo)

**Comment by Pony-Stark** [comment]
[Mathjax live Preview](https://www.mathjax.org/#demo) thanks for this
Sorry for the typo. I meant to say that
\(\sec x \cos 5 x+1=0, 0<x<\frac{\pi}{2}\) is not working.

Works fine after introducing space between < and x. The issue is with mathjax itself and not with flutter-tex.
\(\sec x \cos 5 x+1=0, 0< x<\frac{\pi}{2}\)

**Comment by shah-xad** [comment]
Yup, it's from mathjax.
