### ISSUE TITLE
Large images get cut width-wise

### ISSUE THREAD

**Issue by Seamate** [shah-xad/flutter_tex#126]
I am using Flutter Tex in a mobile app built with Flutter and I have this issue where large content like images are cut width-wise and are not scrollable.
Please refer to the image below.
![cropped image](https://user-images.githubusercontent.com/35474522/167056757-754b5d61-8bc5-47ee-9600-d63061d5ca1b.png)

How can I get the image to display fully, or scroll the whole image into view?
Thank you.

**Comment by shobhit2101** [comment]
Hi
I was also facing the same issue.
Quick and temporary fix for this problem is to add the 'width : 100%' attribute in the image tag.

**Comment by Seamate** [comment]
Thanks for the answer, bro! I'll definitely give it a try and let you know how it goes.

**Comment by shah-xad** [comment]
Set custom dimensions. You have full control over HTML with latex code..
