### ISSUE TITLE
Example doesnt work - probably screen size issue

### ISSUE THREAD

**Issue by rdinkel** [shah-xad/flutter_tex#14]
Hi,
first thank you for this but unfortunately the example doesn't work.

Virtual Device:
3.7" 
480x854
API 21 Android 5.0

Issue: 
The screen below the Appbar is empty.

Logs:

`W/PlatformViewsController( 3279): Creating a virtual display of size: [480, 1172] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [480, 854].`

**Comment by shah-xad** [comment]
It's just a warning, Every thing is fine regarding screen size.
