### ISSUE TITLE
The plugin `flutter_tex` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by omishali** [shah-xad/flutter_tex#141]
Hi,
Upon installing the new version on Flutter using `flutter pub add flutter_tex` I get the following notice:
*The plugin `flutter_tex` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider        
removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.*

Is it possible to migrate the plugin to the V2 embedding?
Thanks,
Oren

**Comment by shah-xad** [comment]
It's been fixed.
