### ISSUE TITLE
flutter_tex

### ISSUE THREAD

**Issue by ranjannisha** [shah-xad/flutter_tex#15]
URL: https://pub.dev/packages/flutter_tex

Hi,
I am not able to make text(latex) clickable for my quiz to submit the correct answer.
Thanks in Advance!!!

**Comment by jmanns** [comment]
It doesn't pick up the tap gesture, I presume this is because a web view is returned. You could try using the double tap gesture or else use a stack and have a transparent container placed over the TexView.

**Comment by ranjannisha** [comment]
Thanks!!! I just got double tap gesture but i dint get using stack. 
Can you send me the code?
