### ISSUE TITLE
TeXView is selectable by default when hover over it in flutter web

### ISSUE THREAD

**Issue by Harishpenta** [shah-xad/flutter_tex#155]
TeXView(
          child: TeXViewDocument(
            mathMLContent,
            style: TeXViewStyle(
              fontStyle: TeXViewFontStyle(
                fontSize: isBold ? 20 : 20,
                fontFamily: "Manrope",
                fontWeight:
                isBold ? TeXViewFontWeight.w500 : TeXViewFontWeight.normal,
              ),
            ),
          ),
          renderingEngine: const TeXViewRenderingEngine.mathjax(),)
        
        
        
i don't want to make this text as selectable, how to disable the selection?

**Comment by shah-xad** [comment]
You can pass something in HTML with your lateX code.
