### ISSUE TITLE
webview_flutter_plus dependency issues in other packages

### ISSUE THREAD

**Issue by MishaCM** [shah-xad/flutter_tex#157]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:** yes

Please provide an update to the package as some of the other packages that has dependency over webview_flutter facing version compatibility issues. 

Because flutter_widget_from_html >=0.10.1 <0.11.0-alpha.1 depends on fwfh_webview ^0.7.0+2 which depends on webview_flutter ^4.0.1, flutter_widget_from_html >=0.10.1 <0.11.0-alpha.1 requires webview_flutter ^4.0.1.
Because webview_flutter_plus 0.3.0+2 depends on webview_flutter ^3.0.1 and no versions of webview_flutter_plus match >0.3.0+2 <0.4.0, webview_flutter_plus ^0.3.0+2 requires webview_flutter ^3.0.1.
Thus, flutter_widget_from_html >=0.10.1 <0.11.0-alpha.1 is incompatible with webview_flutter_plus ^0.3.0+2.
And because flutter_tex 4.0.3+4 depends on webview_flutter_plus ^0.3.0+2 and no versions of flutter_tex match >4.0.3+4 <5.0.0, flutter_widget_from_html >=0.10.1 <0.11.0-alpha.1 is incompatible with flutter_tex ^4.0.3+4.

**Comment by LipJ01** [comment]
Is there any work around for this?

**Comment by shah-xad** [comment]
It's been fixed.
