### ISSUE TITLE
i want to disable right click on texview in flutter web

### ISSUE THREAD

**Issue by srushtiCloudus** [shah-xad/flutter_tex#158]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:**

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer:**

**Comment by shah-xad** [comment]
You can pass something like this: https://stackoverflow.com/questions/62244113/can-i-change-right-click-action-in-flutter-web-application in your HTML code
