### ISSUE TITLE
Add support for flutter-web

### ISSUE THREAD

**Issue by JasMich** [shah-xad/flutter_tex#16]
Do you think you may support Flutter Web?

**Comment by shah-xad** [comment]
Flutter doesn't support plugin system, and for web you can directly use MathJax in your Html.

**Comment by maheshbhattaraai** [comment]
html syntax delays to load inside TexView and performance is also slow.

**Comment by shah-xad** [comment]
Flutter web support has been added.

**Comment by JasMich** [comment]
Alternatively you could use `latex_flutter` (https://pub.dev/packages/katex_flutter) which renders much faster than this due to the KaTeX library.

**Comment by shah-xad** [comment]
@JasMich nice effort but katex_flutter won't work offline. It's speed depends on the Internet connection.
