### ISSUE TITLE
Does this package support all HTML tags?

### ISSUE THREAD

**Issue by SunnyBun-ny** [shah-xad/flutter_tex#161]
I want show this HTML Script in my flutter app

```<ol>\n\t<li>\n\t<h1 style=\"text-align: center;\"><s><em><strong>\\(x = {-b \\pm \\sqrt{b^2-4ac} \\over 2a}\\)</strong></em></s></h1>\n\t</li>\n\t<li><s><em><strong>hyrxdl;l</strong></em></s></li>\n\t<li><s><em><strong>ujj</strong></em></s></li>\n</ol>```

Latex is rendering great but ol and li are not being shown
<img src="https://github.com/shah-xad/flutter_tex/assets/79015550/9032ab7c-5c54-4c69-8b22-4195e8976776" alt="Screenshot_1695902142" width="300" >

**Comment by shah-xad** [comment]
It must work as all widgets are made using HTML, try to run your code separately in a browser and then try.
