### ISSUE TITLE
TeXViewRenderingEngine katex();  $Package's mathematical formula $...  $, and does not translate into a mathematical formula

### ISSUE THREAD

**Issue by MisterZhu** [shah-xad/flutter_tex#164]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:**
Yes

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer:**
RenderingEngine: TeXViewRenderingEngine katex();  $Package's mathematical formula $...  $, and does not translate into a mathematical formula, shouldn't he be inline?  I would like to know how to implement $...  How does the mathematical formula for the $package display correctly?  The problem picture is shown below

![IMG_0026](https://github.com/shah-xad/flutter_tex/assets/16483352/c39c09a2-789e-4550-8c44-c1212ed6f422)
![IMG_0027](https://github.com/shah-xad/flutter_tex/assets/16483352/f42b2006-9520-4ea5-8beb-bdb4bf30fda0)

**Comment by MisterZhu** [comment]
This is the code I used
Figure 1 is renderingEngine: TeXViewRenderingEngine katex (),
Figure 2 is renderingEngine: TeXViewRenderingEngine mathjax (),
But now I need renderingEngine: TeXViewRenderingEngine katex (), can display properly
Related code：
TeXView mathdown(String content) {
  String str = r"""Calculus is a branch of mathematics that deals with the derivatives and integrals of functions. Here is an example calculus:
Example: Find the derivative of the function $f(x)=x^3$at $x=2$.
Solution: Using the derivation formula, we can find the derivation of $f'(x)$:
$$f'(x) = 3x^2$$
Then, put $x=2$into $f'(x)$to get:
$$f'(2) = 3(2)^2 = 12$$
Thus, the derivative of the function $f(x)$at $x=2$is $12$.""";
    return TeXView(
      renderingEngine: TeXViewRenderingEngine.katex(),
      child:
      TeXViewDocument(
        str,
        style: TeXViewStyle(
          margin: TeXViewMargin.only(top: 10),
          fontStyle: TeXViewFontStyle(
            fontSize: 16,
          ),
          contentColor: TBDefVal.chatRegularColor,
        ),
        // 设置字体颜色
      ),
      style: const TeXViewStyle(
        backgroundColor: Colors.white,
      ),
    );
  }

**Comment by MisterZhu** [comment]
This is the code I used
Figure 1 is renderingEngine: TeXViewRenderingEngine katex (),
Figure 2 is renderingEngine: TeXViewRenderingEngine mathjax (),
But now I need renderingEngine: TeXViewRenderingEngine katex (), can display properly
Related code：
```
TeXView mathdown(String content) {
  String str = r"""Calculus is a branch of mathematics that deals with the derivatives and integrals of functions. Here is an example calculus:
Example: Find the derivative of the function $f(x)=x^3$at $x=2$.
Solution: Using the derivation formula, we can find the derivation of $f'(x)$:
$$f'(x) = 3x^2$$
Then, put $x=2$into $f'(x)$to get:
$$f'(2) = 3(2)^2 = 12$$
Thus, the derivative of the function $f(x)$at $x=2$is $12$.""";
    return TeXView(
      renderingEngine: TeXViewRenderingEngine.katex(),
      child:
      TeXViewDocument(
        str,
        style: TeXViewStyle(
          margin: TeXViewMargin.only(top: 10),
          fontStyle: TeXViewFontStyle(
            fontSize: 16,
          ),
          contentColor: TBDefVal.chatRegularColor,
        ),
        // 设置字体颜色
      ),
      style: const TeXViewStyle(
        backgroundColor: Colors.white,
      ),
    );
  }
```

**Comment by shah-xad** [comment]
use \(your latex code\) for inline rendering.
