### ISSUE TITLE
Error: Unable to load asset: "favicon.ico".

### ISSUE THREAD

**Issue by MishaCM** [shah-xad/flutter_tex#165]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:** Yes

Error: Unable to load asset: "favicon.ico".

This error keeps showing in console when try to render html content to the view.

**Comment by shah-xad** [comment]
That doesn't harm anything. It still works.
