### ISSUE TITLE
WebView.destroy() called while WebView is still attached to window.

### ISSUE THREAD

**Issue by todaysprint** [shah-xad/flutter_tex#167]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:**

**Question:**  W/cr_AwContents(32453): WebView.destroy() called while WebView is still attached to window.
E/chromium(32453): [ERROR:aw_browser_terminator.cc(156)] Renderer process (22539) crash detected (code -1).

**Comment by shah-xad** [comment]
You were using an outdated version; please try the latest one now.
