### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by maheshbhattaraai** [shah-xad/flutter_tex#17]
> Poor performance inside list.builder.

**Comment by shah-xad** [comment]
> > Poor performance inside list.builder.

can you show your code?

**Comment by maheshbhattaraai** [comment]
`
var text = r"""
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$<br>
""";

ListView.builder(
   itemCount:50,
   itemBuilder:(BuildContext context,int index){
      return TeXView(
            teXHTML : text,
     );
  }
)
`

> You ever tried in in ListView.builder this is very laggy in performance . I think it is rendered inside web view . While scroll down up it is re-rendered which is slow down performance. test it.
But Thanks for your package it is very useful.

**Comment by shah-xad** [comment]
I have updated the plugin, please try the latest version , now it'll not rerender again and again.

**Comment by maheshbhattaraai** [comment]
html syntax delays to load inside TexView and performance is also slow.

**Comment by shah-xad** [comment]
Yes performance has been optimized please consider 1.0.13 version.

**Comment by shah-xad** [comment]
Speed has been optimized by adding Katex support a much faster renderer than MathJax, Please consider latest version ` flutter_tex: ^3.0.0` and use `renderingEngine: RenderingEngine.Katex` for optimized speed.
