### ISSUE TITLE
Error: The method 'loadAssetServer' isn't defined for the class 'WebViewControllerPlus'

### ISSUE THREAD

**Issue by sthakrishnakumar** [shah-xad/flutter_tex#172]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:** Yes

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer:** 

Error (Xcode): ../../../.pub-cache/hosted/pub.dev/flutter_tex-4.0.5/lib/src/views/tex_view_mobile.dart:22:9: Error: The method 'loadAssetServer' isn't defined for the class 'WebViewControllerPlus'.

**Comment by vishal-tranzita** [comment]
i got same issue for my flutter mobile application.

**Comment by shah-xad** [comment]
It's been fixed, please upgrade.
