### ISSUE TITLE
Rendering lag, with emulator and mobile

### ISSUE THREAD

**Issue by AnAnD4T1** [shah-xad/flutter_tex#18]
I storing latex code in firebase and getting to a pageview, but when i scroll through pages i am having rendering lags.

**Comment by shah-xad** [comment]
Problem has been solved.

**Comment by AnAnD4T1** [comment]
Thanks you

**Comment by shah-xad** [comment]
Speed has been optimized by adding Katex support a much faster renderer than MathJax, Please consider latest version ` flutter_tex: ^3.0.0` and use `renderingEngine: RenderingEngine.Katex` for optimized speed.

**Comment by AnAnD4T1** [comment]
Thanks,
