### ISSUE TITLE
Delay Rendering(It takes almost 15-20 sec for rendering)

### ISSUE THREAD

**Issue by maheshbhattaraai** [shah-xad/flutter_tex#19]
> It takes much time for rendering in app. I am fetching webview from server . Content is containing 
   html and latex code. And another issue is while we using animation on page in which i am using 
   texview , it is rerender while using animation.

**Comment by shah-xad** [comment]
I don't think it's taking 15-20 sec for rendering, Please consider the latest version 1.0.12  and the other issue has been solved, please check that.

**Comment by maheshbhattaraai** [comment]
May be this is due to mathjax inside webview so it takes time to render . Getting latex with html mixed string from api which has to render in ListView. It is very laggy in performance when it doesnot completely render. Have you ever tried.

**Comment by shah-xad** [comment]
Yeah, it may be, but did you try the example? It also has much data to render but it doesn't take as much time as you mentioned, Now I have updated the example please do consider that in 1.0.13, again new update :laughing:

**Comment by maheshbhattaraai** [comment]
If we can get image only for latex to render using javascript engine with mathjax . This plugin would be awesome.

**Comment by shah-xad** [comment]
Ok I'll try for that, BTW Speed has been optimized by adding Katex support a much faster renderer than MathJax, Please consider latest version ` flutter_tex: ^3.0.0` and use `renderingEngine: RenderingEngine.Katex` for optimized speed.

**Comment by maheshbhattaraai** [comment]
Ok sure. But i tried katex plugin this is also had rendering performance issue in listview builder. But i am going through this also. We should work on performance for listview.builder .

**Comment by shah-xad** [comment]
I have mentioned in readme and would also suggest you not to use so many TeXView in single page i.e. ListView as TeXView depends on WebView which a heavy View. Please do give a try with renderEngine. Katex and you'll observe a huge change..

**Comment by maheshbhattaraai** [comment]
Ok

**Comment by maheshbhattaraai** [comment]
Any further plan for listview.builder .

**Comment by shah-xad** [comment]
Please share your code so I can see what's the actual issue.
