### ISSUE TITLE
Flutter Web Not running and Hangs Chrome

### ISSUE THREAD

**Issue by sehbanalam** [shah-xad/flutter_tex#20]
Following Error was thrown.

throw_ (package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart:196:49)
_bind (package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart:455:5)
bind (package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/socket.dart:336:27)
bind (package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http_impl.dart:2694:10)
bind (package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http.dart:229:19)

**Comment by shah-xad** [comment]
Currently it's not for flutter web.

**Comment by shah-xad** [comment]
I have added Flutterweb support.
