### ISSUE TITLE
glitchy and slow on render

### ISSUE THREAD

**Issue by jshepin** [shah-xad/flutter_tex#21]
When the app starts, first the raw text is displayed for a fraction of a second and then it renders the equations, this looks really bad, how can I prevent this? also, it takes 1.5-2 seconds after the app has already loaded, making this unusable for a menu based application where the user will have to wait this time many times throughout their session.

**Comment by jshepin** [comment]
I found [this](https://stackoverflow.com/questions/30855985/pure-css-animation-visibility-with-delay) which works, for those who need a band-aid solution but there must be a different better solution.

**Comment by shah-xad** [comment]
The rendering flashes issue has been solved, please check the latest version 1.0.12

**Comment by shah-xad** [comment]
Speed has been optimized by adding Katex support a much faster renderer than MathJax, Please consider latest version ` flutter_tex: ^3.0.0` and use `renderingEngine: RenderingEngine.Katex` for optimized speed.
