### ISSUE TITLE
National characters

### ISSUE THREAD

**Issue by kadamowi** [shah-xad/flutter_tex#22]
I have problem with polis language.
I this case 
```
                    child: TeXView(
                      teXHTML: r"$$Pole\ trójkąta = \frac{1}{2}ah$$",
                      loadingWidget: Center(
                         child: Text("Kalkulacja"),
                      ),
```
the polish letter between k and t looks after rendering little different.
Is this correct use ?

**Comment by shah-xad** [comment]
Please try with the latest version flutter_tex: ^3.0.0 and use renderingEngine: RenderingEngine.Katex .

**Comment by shah-xad** [comment]
I think you are putting everything between $$ and rendering engine is trying to render everything I would suggest you go like this.

```
r"Pole trójkąta = \(\frac{1}{2}ah\) <br>"
or escape that particular text like
r" $$Pole\ \text{trójkąta} = \frac{1}{2}ah$$"
```
