### ISSUE TITLE
any way to support mathml format

### ISSUE THREAD

**Issue by dhruvinprajapati** [shah-xad/flutter_tex#25]
Thank you for great work.

Is there any way to render mathml format.

Any kind of help will be appreciated .

**Comment by shah-xad** [comment]
Did you try with Katex Rendering Engine? Katex by default supports mathml.

**Comment by shah-xad** [comment]
I have added katex configuration while selecting katex rendering engine where you can configure katex options and mathml format can be configured there.

**Comment by shah-xad** [comment]
MathML Support has been added, please consider `flutter_tex: ^4.0.0`
