### ISSUE TITLE
Questions on android manifest permissions

### ISSUE THREAD

**Issue by flutternoob** [shah-xad/flutter_tex#27]
Hi, nice work with this package. I wanted to know though - why are internet and network access permissions needed? I have created an app that works fine without these permissions.

**Comment by shah-xad** [comment]
Glad to know this if it's working fine without these permissions but I'll suggest you to keep these permissions as flutter_tex runs a local server to render the HTML and TeX code, therefore it may cause problems. It'll also work without WAKE_LOCK permission but it'll cause issues when you'll put too many views in a single page,

**Comment by flutternoob** [comment]
OK thanks

**Comment by shah-xad** [comment]
Yes WAKE_LOCK will definitely solve the problem.
