### ISSUE TITLE
is it possible to make the background transparent?

### ISSUE THREAD

**Issue by IhwanID** [shah-xad/flutter_tex#29]
Hi, @shah-xad. I use your package to render MathJax syntax. it's so useful, but it's possible to make the background transparent or change the color background (currently only white)?  
actually I just need the text only without white background like Text Widget.

**Comment by shah-xad** [comment]
Yes you can change any color of the background, `flutter_tex` have full HTML and JS support you can create your own div and put your code into and style it as you wish. just try this,

```dart

String katexTeXHTML = r"""
<style>
#mycustomdiv{
  background-color: lightblue;
}
</style>

<div id="mycustomdiv">
     A simple Example to render \( \rm\\TeX \) in flutter with full <B>HTML</B> support<br><br>
 
     When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
 
     $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$<br>
</div>   """;
```

if you want to change color of complete teXView you can use this, 

```
<style>
#teXHTML {
  background-color: lightblue;
}
</style>
```

**Comment by IhwanID** [comment]
Thanks, sir but that's not I actually mean. 

if I wrap TeXView in the Container like this. the background of TextView is still white and only the text is lightblue. you know what i mean right?

`
Container(
                color: Colors.yellow,
                child: TeXView(
                  teXHTML: r"""
                      <style>
                      #teXHTML {
  background-color: lightblue;
}
                      </style>
                      $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$<br> 
                      """,
                  renderingEngine: RenderingEngine
                      .Katex, // Katex for fast render and MathJax for quality render.
                  onRenderFinished: (height) {
                    print("Widget Height is : $height");
                  },
                  onPageFinished: (string) {
                    print("Page Loading finished");
                  },
                ),
              ),
`
![image](https://user-images.githubusercontent.com/28101696/78898148-87802d80-7a9d-11ea-8dc1-63847ec0ff85.png)

**Comment by IhwanID** [comment]
Thanks sir. i just need to set the height so the the white color gone.
