### ISSUE TITLE
Handle onPressed / onTap

### ISSUE THREAD

**Issue by IhwanID** [shah-xad/flutter_tex#30]
Hi @shah-xad , i have a new issue. right now it's hard to create onTap / onPressed. i have wrapped in GestureDetector / Button Widget but if I click the TeXView there's nothing happen. I guess it's because the TeXView is based on WebView. so any idea?

**Comment by shah-xad** [comment]
Just put it into the children of the  `Stack` widget and below it add `Positioned.fill ` having child `Inkwell`. Then you can use `Inkwell's` onTap() method.

**Comment by shah-xad** [comment]
I have updated the package and added `onTap` method please upgrade to latest version `flutter_tex: ^3.1.4`

**Comment by IhwanID** [comment]
I have updated in ^3.1.4 version. sure there is onTap method but the text is not loaded, loading only for a long time.

**Comment by IhwanID** [comment]
thank you sir

**Comment by kunalgoel313** [comment]
I am facing the same issue in flutter web but this solution is not working. Do you have any other way for web
