### ISSUE TITLE
Rendering on ios taking minutes

### ISSUE THREAD

**Issue by jshepin** [shah-xad/flutter_tex#31]
Hi, I ran the example code with the most recent version of flutter_tex and the rendering with both mathjax and katex taking forever, and i mean forever to load on the simulator. I've used this in the past and it never takes this long, it's frankly unusable. I just get the blue spinner and if I wasn't patient, I wouldn't say it would spin infinitely. I did, however, install your android demo app and it worked great and quickly, so im not sure what happened on the ios side of things. 

*UPDATE* 
After running the demo app on my physical device it works great, so im wondering if its just an issue with the simulator
cheers

**Comment by shah-xad** [comment]
I am so sorry for the inconvenience. Did you try both android emulator and iOS simulator??

**Comment by jshepin** [comment]
Thank you for your response, you don't have to be sorry, for now i think this is an issue with my system. not yours. I will close, thanks :)
