### ISSUE TITLE
Not working on flutter web production was deploy on firebase hosting

### ISSUE THREAD

**Issue by phamnhuvu-dev** [shah-xad/flutter_tex#33]
It worked on localhost with debug mode.
But when build release and deploy to firebase hosting I just see this error.

> Uncaught (in promise) SecurityError: Failed to register a ServiceWorker for scope ('https://mywebsite/packages/flutter_tex/src/tex_libs/mathjax/') with script ('https://mywebsite/packages/flutter_tex/src/tex_libs/mathjax/flutter_service_worker.js'): The script has an unsupported MIME type ('text/html').

**Comment by shah-xad** [comment]
This problem has been solved please consider latest version `flutter_tex: ^3.1.4+1`.
Here it's working https://flutter-tex.web.app/#/
