### ISSUE TITLE
add custom background support

### ISSUE THREAD

**Issue by jshepin** [shah-xad/flutter_tex#34]
Hi, 
  It would be really great if you could add a custom background parameter the TeXView class. Although a background can be specified by wrapping your HTML in a div with css, it doesn't change the color of the entire TeXView. That way dark themes or transparent backgrounds could be possible.

**Comment by shah-xad** [comment]
Yes, you are right but as you now this package is based on `webview_flutter` and currently there's no way to make it transparent.

**Comment by shah-xad** [comment]
I have added styling in flutter_tex now you can customize each and everything, please updated it to 3.5.0 version and check it. Be careful there are API changes please do check the example before proceeding.

**Comment by jshepin** [comment]
This is wonderful!
