### ISSUE TITLE
E/flutter (26142): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unable to add window android.view.ViewRootImpl$W@bfe683a -- the specified display can not be found, null)

### ISSUE THREAD

**Issue by jshepin** [shah-xad/flutter_tex#35]
I experienced this issue when running my working app (for mobile phones) on a pixel C tablet simulator.

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unable to add window android.view.ViewRootImpl$W@bfe683a -- the specified display can not be found, null)
E/flutter (26142): #0      <optimized out> (<optimized out>:569)
E/flutter (26142): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter (26142): <asynchronous suspension>
E/flutter (26142): #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:552)
E/flutter (26142): <asynchronous suspension>
E/flutter (26142): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175)
E/flutter (26142): <asynchronous suspension>

**Comment by shah-xad** [comment]
Is it a device specific issue or you facing it on all devices?

**Comment by jshepin** [comment]
As of my testing, its entirely an issue with the Pixel C tablet simulator. I have the app working properly on my Samsung phone, Pixel 3 Simulator

**Comment by shah-xad** [comment]
I just tried this on Pixel C tablet emulator and everything is perfect, IDK why are you facing this issue in that particular emulator.
