### ISSUE TITLE
no rendering on ios at all on simulator or physical device

### ISSUE THREAD

**Issue by jshepin** [shah-xad/flutter_tex#36]
<img width="269" alt="Screen Shot 2020-04-28 at 10 43 53 PM" src="https://user-images.githubusercontent.com/31457361/80558987-d684f880-89a1-11ea-8ba6-1b11c113266b.png">
There are no errors listed, my info.plist contains the necessary edit, and nothing is displayed using the demo app. Also, no errors are given. using version "flutter_tex: ^3.1.4+1"

**Comment by hcakil** [comment]
check iOS implementation lines in Info.plist

<key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key> <true/>
  </dict>
<key>io.flutter.embedded_views_preview</key> <true/>
