### ISSUE TITLE
Mysterious 10-15px padding/margin at the bottom of texview 

### ISSUE THREAD

**Issue by jshepin** [shah-xad/flutter_tex#38]
I love the new styling features, However, I have encountered a white bar at the bottom of the view that I can't seem to get rid of. In your example code, if you remove all the padding and the border-radius, you are left with the same issue. The blue border is added to show where the actual content is, but that white bar is not part of my code. I really appreciate your update with the css styling, but this is an eyesore for the dark them :( . Thanks so much - Joseph

![image](https://user-images.githubusercontent.com/31457361/81013110-4111ba80-8e20-11ea-9294-bd189ecc8f3b.png)

`
                                                          return TeXView(
                                                            renderingEngine:
                                                                RenderingEngine.Katex,
                                                            children: [

                                                              TeXViewChild(
                                                                body: snapshot.data[index],
                                                                decoration: TeXViewDecoration(
                                                                  style: TeXViewStyle(
                                                                    border: TeXViewBorder(
                                                                        all: TeXViewBorderDecoration(
                                                                            borderColor:
                                                                                Colors.blue,
                                                                            borderStyle:
                                                                                TeXViewBorderStyle
                                                                                    .Solid,
                                                                            borderWidth: 5)),
                                                                    padding: TeXViewPadding(
                                                                        top: 0, bottom: 0),
                                                                    backgroundColor: dark
                                                                        ? Color(0xff2f3136)
                                                                        : Colors.white,
                                                                    contentColor: dark
                                                                        ? Colors.white
                                                                        : Colors.black,
                                                                  ),
                                                                ),
                                                              )
                                                            ],
                                                            //loadingWidget: Center(
                                                            //    child:
                                                            //        CircularProgressIndicator()),
                                                          );`

**Comment by shah-xad** [comment]
@jshepin  you are right this is an issue, I'll fix it in next update. For a quick fix, you can use negative margins to correct this.

**Comment by shah-xad** [comment]
This issue has been resolved please upgrade to the latest version.

**Comment by shah-xad** [comment]
I am closing this issue as It has been resolved.
