### ISSUE TITLE
Dynamically adding styles to a TeXViewChild refreshes the whole webview

### ISSUE THREAD

**Issue by philipbalbas** [shah-xad/flutter_tex#40]
I'm adding interactivity to some parts of the webview that adds a border and background color to a TeXViewChild. However, changing the style of a TeXViewChild also causes the entire webview to refresh.

 Is there a way around this?

**Comment by shah-xad** [comment]
Sorry, currently there's no way to do this. I'll try to handle this issue in the next update.

**Comment by shah-xad** [comment]
Hi, I have added a new widget `TeXViewGroup` in the new version 3.6.3. If you want to create a quiz app It'll help you to create as you want, just check the example before proceeding.

**Comment by philipbalbas** [comment]
Saw this a bit late but thanks for this! Will definitely help speed up my app!
