### ISSUE TITLE
ImeThread is not enabled

### ISSUE THREAD

**Issue by Mahmud-CSE16** [shah-xad/flutter_tex#41]
**TeXView can't show any text. It shows ImeThread is not enabled.**

**my code:**
```dart
TeXView(
                renderingEngine: RenderingEngine.Katex,
                children: [
                  TeXViewChild(
                      id: "child_1",
                      title: r"<h3>Quadratic Equation</h3>",
                      body: r"""<p>
                                   When \(a \ne 0 \), there are two solutions to \(ax^2 + bx + c = 0\) and they are
                                   $$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$</p>""",
                      decoration: TeXViewDecoration(
                          style: TeXViewStyle(
                            backgroundColor: Colors.green,
                            contentColor: Colors.white,
                          ),
                          titleStyle: TeXViewStyle(
                            textAlign: TeXViewTextAlign.Center,
                            backgroundColor: Colors.red,
                            contentColor: Colors.white,
                          ),
                          bodyStyle: TeXViewStyle.fromCSS(
                              "color:white;background-color:light-green")))
                ],
                style: TeXViewStyle(
                  elevation: 10,
                  border: TeXViewBorder(
                      all: TeXViewBorderDecoration(
                          borderColor: Colors.blue,
                          borderStyle: TeXViewBorderStyle.Solid,
                          borderWidth: 5)),
                  backgroundColor: Colors.white,
                ),
                loadingWidget: Center(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      CircularProgressIndicator(),
                      Text("Rendering with ")
                    ],
                  ),
                ),
                onTap: (childID) {
                  print("TeXView $childID is tapped.");
                }),
```

**Console shows:**
```dart
D/Surface ( 5430): Surface::setBufferCount(this=0x8ae13f00,bufferCount=4)
D/WebView ( 5430): loadUrl(extra headers)=http://localhost:5353/packages/flutter_tex/src/tex_libs/katex/index.html?teXViewServerPort=5353
I/cr_Ime  ( 5430): ImeThread is not enabled.
```
**flutter doctor shows:**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.18.0-12.0.pre, on Microsoft Windows
    [Version 10.0.18362.720], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!
```
Please help how to over come this issue.

**Comment by shah-xad** [comment]
please show me your `flutter doctor` output

**Comment by Mahmud-CSE16** [comment]
> please show me your `flutter doctor` output
After run flutter doctor shows below things. looks like ok. No issues found.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.18.0-12.0.pre, on Microsoft Windows
    [Version 10.0.18362.720], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

**Comment by shah-xad** [comment]
Did you try with Stable or Beta channel?

**Comment by Mahmud-CSE16** [comment]
> Did you try with Stable or Beta channel?

Stable.

the version is flutter_tex 3.5.1

**Comment by Mahmud-CSE16** [comment]
> Did you try with Stable or Beta channel?

console shows also this message below:
```
I/chromium(14145): [INFO:CONSOLE(0)] "XMLHttpRequest cannot load http://localhost:null/?query=getRawTeXHTML. Cross origin requests are only supported for protocol schemes: http, data, chrome, https.", source: http://localhost:5353/packages/flutter_tex/src/flutter_tex_libs/mathjax/index.html?teXViewServerPort=5353&viewInstanceCount=1&configurations=%22%7B%7D%22 (0)
```

**Comment by shah-xad** [comment]
> > Did you try with Stable or Beta channel?
> 
> console shows also this message below:
> 
> ```
> I/chromium(14145): [INFO:CONSOLE(0)] "XMLHttpRequest cannot load http://localhost:null/?query=getRawTeXHTML. Cross origin requests are only supported for protocol schemes: http, data, chrome, https.", source: http://localhost:5353/packages/flutter_tex/src/flutter_tex_libs/mathjax/index.html?teXViewServerPort=5353&viewInstanceCount=1&configurations=%22%7B%7D%22 (0)
> ```

Did you follow all this??

For **Android** Make sure to add this line `android:usesCleartextTraffic="true"` in your `<project-directory>/android/app/src/main/AndroidManifest.xml` under `application` like this.
```xml
<application
       android:usesCleartextTraffic="true">
</application>
```

and permissions

```xml
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
```

For **iOS** add following code in your `<project-directory>/ios/Runner/Info.plist`
```plist

<key>NSAppTransportSecurity</key>
  
  <dict>
    <key>NSAllowsArbitraryLoads</key> <true/>
  </dict>

<key>io.flutter.embedded_views_preview</key> <true/> 
```

**Comment by Mahmud-CSE16** [comment]
> @Mahmud-CSE16 Did you follow all this??
> 
> For **Android** Make sure to add this line `android:usesCleartextTraffic="true"` in your `<project-directory>/android/app/src/main/AndroidManifest.xml` under `application` like this.
> 
> ```
> <application
>        android:usesCleartextTraffic="true">
> </application>
> ```
> 
> and permissions
> 
> ```
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
>     <uses-permission android:name="android.permission.WAKE_LOCK" />
> ```
> 
> For **iOS** add following code in your `<project-directory>/ios/Runner/Info.plist`
> 
> ```plist
> <key>NSAppTransportSecurity</key>
>   
>   <dict>
>     <key>NSAllowsArbitraryLoads</key> <true/>
>   </dict>
> 
> <key>io.flutter.embedded_views_preview</key> <true/> 
> ```

yes I follow this procedure.

It's working for API level 28(android version 9). I checked by Xiaomi Redmi Note 7 Pro.

**But it can't work for API level 23(android version 6). I checked by Walton Primo NH2 Lite.**

**Comment by shah-xad** [comment]
Yes, you are right there's some issue in the flutter_webview as it's not running JavaScript properly on lower APIs.

**Comment by Mahmud-CSE16** [comment]
> Yes, you are right there's some issue in the flutter_webview as it's not running JavaScript properly on lower APIs.

But flutter_tex: ^3.1.4+1 was working fine.

**Comment by shah-xad** [comment]
Yes it was working but after that, I put javascript code with new syntax, and old browsers are not supporting it. I need to correct JS syntax and I'll update it soon.

**Comment by shah-xad** [comment]
Please try with latest version `flutter_tex: ^3.6.1+1`. It's fixed now.
