### ISSUE TITLE
how to create outside of Textview margin transparent?

### ISSUE THREAD

**Issue by IhwanID** [shah-xad/flutter_tex#46]
Dear @shah-xad , i look into the new update. that's very great. you provide so many new properties. but I wondering, If i give the margin for my TexView, how to create the outside margin transparent, or like I rounded my TexView corner like a cardview bur the outside corner still with white color. how to fix it, any idea?

**Comment by shah-xad** [comment]
@IhwanID sorry that's not possible because currently there's no way to make webview background transparent. Alternatively, you can use margin zero of TeXView and put it into a CardView.

**Comment by IhwanID** [comment]
Nice. thank you
