### ISSUE TITLE
Bug: flutter tex web not working 

### ISSUE THREAD

**Issue by suchibrata** [shah-xad/flutter_tex#49]
Inside web_tex_view.dart in the _getTeXViewUrl in the return statement when you are forming the URL,
query parameter **rawTeXHTML** should named **urlRawTeXHTML**.

It is being accessed as **urlRawTeXHTML** inside flutter_tex.js

**Comment by shah-xad** [comment]
Yes you are right, there are also so many other issues regarding web and I am working on those right now, I 'll update that soon.

**Comment by shah-xad** [comment]
I have solved that particular issue, you can check it here [https://flutter-tex.web.app](https://flutter-tex.web.app)
but there's still an issue on `setState` everything disappears in Flutter Web, rest is almost fine. For that, you can open new issue and I am closing this.

**Comment by suchibrata** [comment]
Thank you. 

For setState to work you have to move this assignment :**viewId = UniqueKey().toString()** in web_tex_view.dart inside this block 
 **if (getRawData() != _lastData) {
...
}**

**Comment by shah-xad** [comment]
> Thank you.
> 
> For setState to work you have to move this assignment :**viewId = UniqueKey().toString()** in web_tex_view.dart inside this block
> **if (getRawData() != _lastData) { ... }**

It didn't work. It's something else I am unable to figure out, see here https://flutter-tex.web.app it even disappears if we hover the cursor over the back button.

**Comment by suchibrata** [comment]
I am using an old version of your code and it is working for me after moving the assignment inside the block. So I could not reproduce this bug. However it is flickering when I move the cursor. 

For this I found two issues being logged with flutter. Please find [here](https://github.com/flutter/flutter/issues/51865)  and [here] (https://github.com/flutter/flutter/issues/53253)

**Comment by shah-xad** [comment]
In old code, I was loading data via URL parameters there wasn't this issue of disappearance just was blinking, but that had so many issues now I am directly accessing Iframe and putting data into that via Javascript, rest everything is fine just this issue of disappearance. I don't have any issue with flickering but data should be there. 
And thanks for those links I'll see those.
