### ISSUE TITLE
How do I display a local image file?

### ISSUE THREAD

**Issue by nilsmechanix** [shah-xad/flutter_tex#51]
Hello,
is it possible to display a local image file from my android studio assets folder?
The raw html code of my TeXViewTeX looks like this:
```
const String _texText = r'''  
<img src="assets\app_icon.png"> <br>
 $$ a^2 = b^2 + c^2 - 2 \, b \, c \cos \alpha $$
<!-- more code -->
''';
```

I've tried
`  <img src="http://localhost:8080/assets/app_icon.png"> <br>`
and
`  <img src="file:///android_asset/flutter_assets/assets/app_icon.png"> <br>`

Thanks

**Comment by shah-xad** [comment]
This time you can use
`        <img src="http://localhost:5353/assets/app_icon.png"> <br>
`
But it's not permanent fix, I'll handle this in next update.

**Comment by nilsmechanix** [comment]
Thanks for the fast replay.


I'll try the code on Monday 




On Wed, May 20, 2020 at 6:17 PM +0200, "Shahzad Akram" <notifications@github.com> wrote:















This time you can use

       <img src="http://localhost:5353/assets/app_icon.png"> <br>

But it's not permanent fix, I'll handle this in next update.

**Comment by shah-xad** [comment]
I have updated the package please take a look at 3.6.2. I have added a new widget `TeXViewImage` where you can load images either from assets or network. Be careful there are some API changes with some new features please do check Changelog and example before proceeding.

**Comment by nilsmechanix** [comment]
The TeXViewImage works like a charme, however I really liked the solution to use 
`<img src="http://localhost:5353/assets/app_icon.png">`
inside the teX string. With the new update that line of code doesn't work anymore. 
The advantage for me to use it inside the teX code is that I can use html style functionality.
I want to be able to show code right next to the image.
In html this can be accomplished by something like this:
`<div>
	<div style:"display: inline-block">
		<img src="drawings\fig1.4.1.svg" alt="figure 1.4.1">
	</div>
	<div style:"display: inline-block">
		$$\begin{aligned} 
        |\mathbf a| &= |\mathbf c|=2, \\[5px]
        |\mathbf d| &= |\mathbf f|=3, \\[5px]
        |\mathbf b| &= 4
        \end{aligned}$$
        </div>	
</div>`
Whats an image src I could use to accomplish this?
Thanks for your help

**Comment by shah-xad** [comment]
Why aren't you using TeXViewImage?

**Comment by shah-xad** [comment]
put TeXViewImage in TeXViewContainer and apply style using TeXviewStyle.fromCSS("your:style;" )

**Comment by nilsmechanix** [comment]
Yes this worked for me. Thanks for the tip.
If I have a page with lots of images and formula right next to that image I have to split the raw teX-String into lots of smaller pieces and then put them back each in a TexViewContainer file.
Since I have to use some containers inside of each other to achive the layout that I want it becomes very nested.
If I could just use the raw HTML and teX code with something like this:
`<img src="http://localhost:5353/assets/app_icon.png"> <br>`
it would become a lot easer for me.
However if this solution can't be available anymore I'll stick with the containers.

**Comment by shah-xad** [comment]
Ok fine you can get port by using this `window.location.port` and just use that port. because this time port is dynamic for each instance, but it won't work properly.
Why don't you create a  custom TeXViewWiget and reuse that again and again?

e.g. for you above code
```

  TeXViewWidget customTeXViewWidget(imgSrc, rawTeX) {
    return TeXViewColumn(children: [
      TeXViewContainer(child: TeXViewImage.asset(imgSrc),
          style: TeXViewStyle.fromCSS("display: inline-block")),
      TeXViewDocument(
          rawTeX, style: TeXViewStyle.fromCSS('display: inline-block'))
    ]);
  }

```

**Comment by shah-xad** [comment]
Hey now again you can use <img src="http://localhost:5353/assets/app_icon.png"> <br>

**Comment by nilsmechanix** [comment]
Thanks, this works!

**Comment by abdelrahman-abied** [comment]
https://github.com/shah-xad/flutter_tex/issues/135#issuecomment-1406771332
