### ISSUE TITLE
TeXViewGroup doesn't  support multiple choices

### ISSUE THREAD

**Issue by pengjinlong** [shah-xad/flutter_tex#55]
hi, I want to achieve the following effect

![pic](https://s1.ax1x.com/2020/05/29/tmyQtx.png)

but when I dynamically adding styles to a TeXViewDocument refreshes the whole webview, 
I see quiz example, it also doesn't  support multiple choices

**Comment by shah-xad** [comment]
Did you check the [quiz example](https://github.com/shah-xad/flutter_tex/blob/master/example/lib/tex_view_quiz_example.dart)?

**Comment by shah-xad** [comment]
Do you want to select more than 1 choice? Like, checkboxes?

**Comment by pengjinlong** [comment]
> Do you want to select more than 1 choice? Like, checkboxes?

yes, and I want to customize the selected item style, just like the pic above

**Comment by shah-xad** [comment]
Currently, there's no way to do this but you can customize the style of a selected item and a normal item, you can see [example](https://github.com/shah-xad/flutter_tex/blob/master/example/lib/tex_view_quiz_example.dart).
