### ISSUE TITLE
HTML right arrow code &#8594; not rendering

### ISSUE THREAD

**Issue by HimanshuSaikia** [shah-xad/flutter_tex#57]
I was using flutter_tex for displaying contents from database which has html codes like right arrow &#8594; in chemical equations. Flutter_tex fails to render when this is encountered

**Comment by shah-xad** [comment]
Can you share your code? As it's working fine here.

`r"<h4>Quadratic &#8594 Equation</h4>"`

![Screenshot from 2020-06-04 14-44-36](https://user-images.githubusercontent.com/32363363/83741795-178fbd00-a672-11ea-8c6d-c97ffa8f30d0.png)

**Comment by HimanshuSaikia** [comment]
Sorry, I was using an older version, flutter_tex 3.6.1+2. 
Just now, updated to flutter_tex 3.6.6+4 and it's working fine. Thanks a lot for this amazing library and your response bro. Stay safe!
