### ISSUE TITLE
chinese code Garbled

### ISSUE THREAD

**Issue by pengjinlong** [shah-xad/flutter_tex#58]
![t6mM0P.png](https://s1.ax1x.com/2020/06/06/t6mM0P.png)
[![t6nu34.png](https://s1.ax1x.com/2020/06/06/t6nu34.png)](https://imgchr.com/i/t6nu34)

version: flutter_tex: ^3.6.6+5

**Comment by shah-xad** [comment]
Is it Chinese language or some sort of symbols?

**Comment by j33tmane** [comment]
Same issue with local Indian languages

**Comment by shah-xad** [comment]
Thanks for your support for making the flutter_tex package better by pointing towards this issue. Now, this issue has been resolved please consider the latest version of the package.

**Comment by nilsmechanix** [comment]
In german language there used to be an issue with some letters aswell. With the new update thats fixed, too! Keep up the great work!
