### ISSUE TITLE
Equation background color does not render properly in web app

### ISSUE THREAD

**Issue by flutternoob** [shah-xad/flutter_tex#65]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer: Yes**

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer: I have gone through the video, but I am not looking for a feature or enhancement. I am reporting a bug.**

When using the package on the web platform, the background color of the page is partly green while the equation's background color is the color I have set it to. How to fix the problem? I do not wish to set a fixed height for the equation, as it will vary from equation to equation and will make modularizing the code difficult. Code snippet and screenshot of the web app are attached in the Logs.

<details>
<summary>Logs</summary>
Code:

```
TeXView(
      style: TeXViewStyle(backgroundColor: Colors.white, fontStyle: TeXViewFontStyle(fontSize: 20)),
      renderingEngine: TeXViewRenderingEngine.mathjax(),
      child: TeXViewDocument(rawEquationString),
)
```

Screenshot:

![Capture](https://user-images.githubusercontent.com/62204476/84872119-182b4900-b09f-11ea-9fcd-c87794770f83.PNG)

</details>

**Comment by akasher** [comment]
I am facing the same problem, Everything is green until I give it a background colour, even then only the equation gets the required background otherwise its green.
![image](https://user-images.githubusercontent.com/26402416/86255423-b73e5d80-bbd4-11ea-8994-9dd13fb7fbc8.png)

**Comment by flutternoob** [comment]
@shah-xad Has this bug been resolved?

**Comment by shah-xad** [comment]
Sorry for the late but it's resolved.
