### ISSUE TITLE
Cannot render

### ISSUE THREAD

**Issue by DarkKnight1005** [shah-xad/flutter_tex#67]
When rendering equations(from readme and other ones) i have something like this 
![photo5451977167547247988](https://user-images.githubusercontent.com/26900245/85782729-d3a34b80-b737-11ea-9c37-fb1a1e5e3506.jpg)

**Comment by shah-xad** [comment]
Please try the latest version.

**Comment by DarkKnight1005** [comment]
> Please try the latest version.
by removing `android:networkSecurityConfig="@xml/network_security_config"` from android manifest, everything started to work, but i don't understand, why it caused some problems.
