### ISSUE TITLE
tag for inline LaTex

### ISSUE THREAD

**Issue by equisbacon** [shah-xad/flutter_tex#68]
The tag for inline expressions is \( LaTex here\)?
Could you make a param to use custom tags like $$this$$ for a new line equation and $this$ for inline equation?
I'm using json to get the LaTex strings and facing some problems to escape backlashes, I attached one image using the raw string from your examples escaped to json string: "When \\(a \\ne 0 \\), there are two solutions to \\(ax^2 + bx + c = 0\\) and they are\r\n     $$x = {-b \\pm \\sqrt{b^2-4ac} \\over 2a}.$$<br>"

![WhatsApp Image 2020-07-03 at 2 57 29 AM](https://user-images.githubusercontent.com/47310304/86436635-0968a700-bcd9-11ea-8fc6-30e60b6bdffb.jpeg)

**Comment by equisbacon** [comment]
In addition, you did a really really good job, I enjoyed a lot!

**Comment by shah-xad** [comment]
I have added support for inline formula by using delimiter `$..$` for mathjax. You should upgrade to the latest version.
