### ISSUE TITLE
RenderConstrainedBox object was given an infinite size during layout

### ISSUE THREAD

**Issue by jidasheng** [shah-xad/flutter_tex#69]
CRASH:  RenderConstrainedBox object was given an infinite size during layout.
caused by the following simple code:
```dart
MaterialApp(
      title: 'Material App',
      home: Scaffold(
          appBar: AppBar(
            title: Text('Material App Bar'),
          ),
          body: Row(
              children: [
                 Column(children: [Text("asdf")]),
                 Column(children: [TeXView(child: TeXViewDocument("\\(x_3\\)"))]),
              ],
)));
```

**Comment by sudeshkumara** [comment]
@jidasheng  Just wrap your columns from Expanded widgets

Row(
     children: [
          Expanded(
                 flex: 1, // if this value = X(only int)
                 child: Column(children: [Text("asdf")] ),
           ),
           Expanded(
                  flex: 9, // this value will be 10 - X
                  child: Column([TeXView(child: TeXViewDocument("\\(x_3\\)"))]),
     ],
)

**Comment by shah-xad** [comment]
It's not related to `flutter_tex`, consider the solution by @sudeshkumara.
