### ISSUE TITLE
Flutter Web Uncaught ReferenceError: OnPageLoaded is not defined

### ISSUE THREAD

**Issue by BaseChip** [shah-xad/flutter_tex#71]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:** yes, version ^3.6.7+8

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer:** I'm not looking for a Feature

Hey, I'm trying to use flutter_tex in flutter web, but in the last time I always get the error ```Uncaught ReferenceError: OnPageLoaded is not defined
<anonym> http://server_adress/assets/packages/flutter_tex/js/mathjax/index.html:64```
whenever I use a TeXViewWidget. The Text still renders without any problems, but e.g. FloatingActionButtons or any Button at all don't get executed anymore. If I remove TeXViews from the site its all working again.

**Comment by gowtham-xseed** [comment]
+1

**Comment by kuro7766** [comment]
+1

**Comment by Ahmadre** [comment]
@shah-xad

**Comment by shah-xad** [comment]
This has been resolved, please consider the latest version, but still web has issues,
