### ISSUE TITLE
TeXViewTextAlign not working for Left and Right

### ISSUE THREAD

**Issue by Ramin-Bateni** [shah-xad/flutter_tex#77]
My Code is:

```
TeXView(
      child: TeXViewDocument(latex),
      style:    
          TeXViewStyle(
              textAlign: TeXViewTextAlign.Left,
              backgroundColor: Colors.pink[200],
              fontStyle: TeXViewFontStyle(
                  fontFamily: "kalameh",
                  fontSize: 11)),
    );
```
Actual Result:
![image](https://user-images.githubusercontent.com/9051320/92720121-68056d80-f379-11ea-8c9a-a9211501893a.png)
Expected Result:
![image](https://user-images.githubusercontent.com/9051320/92720348-b6b30780-f379-11ea-9729-d8177648f256.png)
**How should I align the latex in its box?**

**Comment by Ramin-Bateni** [comment]
I found the problem. My latex wrapped with `$$` signs. I removed it from `begin `and `and` of the latex.

**Comment by sudeshkumara** [comment]
@Ramin-Bateni  Refer the following pdf for more info :[Link]( https://www.scss.tcd.ie/~dwoods/1617/CS1LL2/HT/wk1/commands.pdf)

But note that not every latex code is as functional as we expected. You need to find another workaround. Let's say if you want to bold some text. You can use \( \textbf{Your Bold Text} \) but it's changing the font size as well. So, then you can simply use \(\small{\textbf{Your Bold Text}}\)
