### ISSUE TITLE
Issue in Readme on Pub

### ISSUE THREAD

**Issue by Vov4yk** [shah-xad/flutter_tex#79]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:** YES

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer:** YES

Guess there is an issue with
```
<key>NSAppTransportSecurity</key>
  <dict>
    <key>NSAllowsArbitraryLoads</key> <true/>
  </dict>Example
<key>io.flutter.embedded_views_preview</key> <true/> 

```
in readme on flutter pub. `Example` is out of tag. It should break info.plist file.

**Comment by hemish11** [comment]
I have created a PR for this. So it would be easier for them to resolve it.
[https://github.com/shah-xad/flutter_tex/pull/80](url)

**Comment by hemish11** [comment]
I think now we can close this issue as the PR created by me is merged and now this error doesn't occur. So we may close it.

**Comment by ComputelessComputer** [comment]
Hi I could not resolve this issue. Is there any source that I can reference on?

**Comment by hemish11** [comment]
This issue is already been resolved. So basically, the readme had Example text in a code snippet that is copied in info.plist. And that Example text should not be there, this issue was to remove it.
