### ISSUE TITLE
Can not get transparent background

### ISSUE THREAD

**Issue by SquarepantsD** [shah-xad/flutter_tex#88]
Hi,

Thank you for creating flutter_tex. I would like to report an issue.
When I set the 'backgroundcolor' to 'transparent' in 'TexViewStyle', it just shows the white background. Then I noticed that there are two layers of backgrounds(three layers if I count the background of the Widget). So l am asking for help about how can I get the 'text' only without any background. 
I attached a screenshot of the problem, I set the backgroundcolor of 'TexViewStyle' to green, and backgroundcolor of widget to 'grey', so you can see the white part where I need it to be transparent.
Best regards
![background of flutter_tex](https://user-images.githubusercontent.com/35415983/103866201-5d2cd080-5100-11eb-863f-d1d2e05802cc.jpg)
![code](https://user-images.githubusercontent.com/35415983/103866215-61f18480-5100-11eb-974c-71da1474f069.jpg)

**Comment by igorbragaia** [comment]
I am facing the same issue.

**Comment by Sivaraj5** [comment]
I am facing the same issue.

**Comment by shah-xad** [comment]
It's been implemented, please consider the latest release.
