### ISSUE TITLE
Not loading in release build apk

### ISSUE THREAD

**Issue by haobk** [shah-xad/flutter_tex#91]
it work in debug mode, but when build release, cannot load content. it issuse by webview_flutter_plus,
webview_flutter_plus cannot load content when build release APK

**Comment by shah-xad** [comment]
Did you add the required permissions?

**Comment by shaikhafzaa2** [comment]
I am facing the same issue even after adding permissions

**Comment by dhanrajdc7** [comment]
I am facing the exact issue. I have added all required permissions. My app renders equations in `Debug Mode`, but NOT in `Release Mode`. 

Can you please look into it? Thank you!
