### ISSUE TITLE
Hide the TexView, till rendering is finished.

### ISSUE THREAD

**Issue by rahulkapoor1** [shah-xad/flutter_tex#99]
**Question:** Are you using the latest version of flutter_tex package? [![pub package](https://img.shields.io/pub/v/flutter_tex.svg)](https://pub.dev/packages/flutter_tex)
**Answer:** Yes

**Question:** If you are looking for a feature, have you watched the [Demo Video](https://www.youtube.com/watch?v=YiNbVEXV_NM) and gone through the [examples folder](https://github.com/shah-xad/flutter_tex/tree/master/example)?
**Answer:** Yes.

**Is there a way to hide the view till rendering is in progress?** 

I tried with Opacity and Visibility Widget.

**Comment by shah-xad** [comment]
Yeah just simply put the `loadingWidgetBuilder` return to null.
